### ISSUE TITLE
Google API Key

### ISSUE THREAD

**Issue by ChrisEdson** [robdyke/NHS-Apps-Library#10]
Hi there -

You have just publicly published a Google API key of ours - can you remove this quite urgently?

https://github.com/robdyke/NHS-Apps-Library/blob/2dfe34c839230081f3f09be1c7e2e852667bcf3c/apps/Second%20Nature/report.json

Chris

**Comment by robdyke** [comment]
Pointing the BFG repo cleaner at it now

**Comment by robdyke** [comment]
It is very easy for secret keys or Api key to be exposed by Apk reverse engineering. There are many ways to protect these secrets though!

[Hiding Secret/Api key in Android](https://medium.com/@rahulsharmagbpec/hiding-secret-api-key-in-android-133eb0440674)

**Comment by ChrisEdson** [comment]
Thank you 🙏😊

We’ll take a look at that ASAP!

**Comment by robdyke** [comment]
This makes me think I should also do a count of API keys found in apps...

**Comment by ChrisEdson** [comment]
Hey - 

Sorry to follow up on this, but the key is still present / the commit still there. Any chance you could take another look?

Chris

**Comment by robdyke** [comment]
I used BFG repo cleaner to purge all the JSON and PDF files from the repo.
Could you please give me an example commit ref?
